### ISSUE TITLE
Issues with binder version

### ISSUE THREAD

**Issue by vitesh13** [vitesh13/DAMASK_workflows#6]
Hi Jan,

I tried the workflow on workstations and it works. 
But on the binder it doesnt work. Currently the error we get is strange, because the fortran files are updated in the Binder repo, so the error "no value found for key microstructure" should not appear. Maybe the binary executable is still referring some old version.

Let us know if you are able to figure this out.

**Comment by jan-janssen** [comment]
Can you be a bit more specific? Which notebook and which cell? 
I tried DAMASK_WORKFLOWS.ipynb and in cell 13 I get:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-13-2d8e39320b71> in <module>
----> 1 d = damask.Result(job_file)
      2 d.add_Cauchy()
      3 d.add_strain_tensor()
      4 d.add_Mises('sigma')
      5 d.add_Mises('epsilon_V^0.0(F)')

/srv/conda/envs/notebook/lib/python3.7/site-packages/damask/_result.py in __init__(self, fname)
     52                 raise TypeError(f'Unsupported DADF5 version {self.version_major}.{self.version_minor}')
     53 
---> 54             self.structured = 'grid' in f['geometry'].attrs.keys()
     55 
     56             if self.structured:

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/srv/conda/envs/notebook/lib/python3.7/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    262                 raise ValueError("Invalid HDF5 object reference")
    263         else:
--> 264             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    265 
    266         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (object 'geometry' doesn't exist)
```

**Comment by vitesh13** [comment]
> DAMASK_WORKFLOWS.ipynb

Hi Jan,

Yes in the DAMASK_WORKFLOWS.ipynb, when you are at the cell 9 (run simulation), you should get the returncode as 0, which would signify successful simulation. On workstations, I get returncode 0. In the binder I was getting 1. I checked the error, it was saying "key microstructure is missing". But this message should not be printed according to the files in the folder (on binder) DAMASK/src/material.f90. Thats why I was under the impression that the binary is perhaps an old one?

I guess the error you got is because the simulation did not run successfully and thats why it did not create the correct object in the HDF5 file. So this also traces back to cell 9. Just check once if your returncode was also 1

**Comment by jan-janssen** [comment]
Can you please update the notebook so the cells are in order? for me cell 9 is:
```
from itkwidgets import view
import itk
```
So it seems the calculation are executed in mixed order.

**Comment by jan-janssen** [comment]
Running it one the command line I get the following error: 
```
cd Examples
DAMASK_grid -l tensionX.load -g test.vtr
```
output: 
```

 <<<+-  DAMASK_interface init  -+>>>

      _/_/_/      _/_/    _/      _/    _/_/      _/_/_/  _/    _/
     _/    _/  _/    _/  _/_/  _/_/  _/    _/  _/        _/  _/
    _/    _/  _/_/_/_/  _/  _/  _/  _/_/_/_/    _/_/    _/_/
   _/    _/  _/    _/  _/      _/  _/    _/        _/  _/  _/
  _/_/_/    _/    _/  _/      _/  _/    _/  _/_/_/    _/    _/


 Roters et al., Computational Materials Science 158:420–478, 2019
 https://doi.org/10.1016/j.commatsci.2018.04.030

 Version: v3.0.0-alpha

 Compiled with: GCC version 7.5.0
 Compiler options: -cpp -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -iprefix /home/conda/feedstock_root/build_artifacts/damask_1600967332552/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/ -isysroot /home/conda/feedstock_root/build_artifacts/damask_1600967332552/_build_env/bin/../x86_64-conda-linux-gnu/sysroot -D_REENTRANT -D DAMASKVERSION="v3.0.0-alpha" -D Grid -D PETSc -isystem /srv/conda/envs/notebook/include -march=nocona -mtune=haswell -auxbase-strip CMakeFiles/DAMASK_grid.dir/DAMASK_interface.f90.o -O2 -O2 -pedantic-errors -Wall -Wextra -Wcharacter-truncation -Wunderflow -Wsuggest-attribute=pure -Wsuggest-attribute=noreturn -Wconversion-extra -Wimplicit-procedure -Wno-unused-parameter-std=f2008 -ftree-vectorize -fstack-protector-strong -fno-plt -ffunction-sections -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/damask_1600967332552/work=/usr/local/src/conda/damask-3.0.0 -fdebug-prefix-map=/srv/conda/envs/notebook=/usr/local/src/conda-prefix -fopenmp -fPIE -ffree-line-length-132 -fimplicit-none -ffpe-summary=all -fdefault-real-8 -fdefault-double-8

 Compiled on: Sep 24 2020 at 17:14:26

 Date: 07/10/2020
 Time: 08:33:36

 MPI processes:    1
 Host name: jupyter-vitesh13-2ddamask-5fworkflows-2dogxcqppj
 User name: jovyan

 Command line call:      DAMASK_grid -l tensionX.load -g test.vtr
 Geometry argument:      test.vtr
 Load case argument:     tensionX.load
 Working directory:      /home/jovyan/Examples
 Geometry file:          test.vtr
 Loadcase file:          tensionX.load
 Solver job name:        test_tensionX

 <<<+-  prec init  -+>>>
 Size of integer in bit:  32
   Maximum value:                 2147483647

 Size of float in bit:    64
   Maximum value:         0.180+309
   Minimum value:         0.223-307
   Decimal precision:     15

 <<<+-  IO init  -+>>>

 <<<+-  config init  -+>>>

 reading material.yaml

 ┌─────────────────────────────────────────────────────────────────────┐
 │                        warning                                      │
 │                         35                                          │
 ├─────────────────────────────────────────────────────────────────────┤
 │ could not get $DAMASK_NUM_THREADS                                   │
 │ BEGIN:      :END                                                    │
 │                                                                     │
 └─────────────────────────────────────────────────────────────────────┘
 using values from config.yaml file

 number of threads:             1


 <<<+-  math init  -+>>>
 size  of random seed:     33
 value of random seed:     -632363681
 start of random sequence:
                           0.41521639173583
                           0.90446034097555
                           0.68770029785695
                           0.81332326425355


 <<<+-  quaternions init  -+>>>

 <<<+-  rotations init  -+>>>

 Rowenhorst et al., Modelling and Simulation in Materials Science and Engineering 23:083501, 2015
 https://doi.org/10.1088/0965-0393/23/8/083501

 <<<+-  YAML_types init  -+>>>

 <<<+-  lattice init  -+>>>

 <<<+-  HDF5_Utilities init  -+>>>

 <<<+-  results init  -+>>>

 Diehl et al., Integrating Materials and Manufacturing Innovation 6(1):83–91, 2017
 https://doi.org/10.1007/s40192-017-0084-5

 <<<+-  discretization_grid init  -+>>>

 ┌─────────────────────────────────────────────────────────────────────┐
 │                        error                                        │
 │                        841                                          │
 ├─────────────────────────────────────────────────────────────────────┤
 │ missing header length info in grid mesh                             │
 │ readGeom                                                            │
 │                                                                     │
 └─────────────────────────────────────────────────────────────────────┘

 DAMASK terminated on:
 Date:               07/10/2020
 Time:               08:33:36
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL IEEE_INEXACT_FLAG
STOP 1
```

**Comment by jan-janssen** [comment]
@vitesh13 Please create an example where the notebook writes the input files and then calls DAMASK. The it should be possible to execute the notebook top to bottom using the "Kernel>Restart & Run All"

**Comment by vitesh13** [comment]
Okay

**Comment by vitesh13** [comment]
The input file basically is the geometry file. This file is being created from scratch.
 With the current version of DAMASK (in the github development), the geometry file can be a .vtr or a .geom file. 
I get this error with the .geom file.
I see that the main cause of this error is: in the material.yaml file, the 'microstructure' has been renamed as 'material'. From the latest development version, 'material' should be acceptable. 
But as it is complaining, the DAMASK version here is an older one. If that is the case, then the changing the word 'material' to 'microstructure' should do the trick. This needs to be checked. 

So this is the error we get right now on running the DAMASK_grid -l tensionX.load -g test.geom on the command line. 
`<<<+-  DAMASK_interface init  -+>>>
 
      _/_/_/      _/_/    _/      _/    _/_/      _/_/_/  _/    _/
     _/    _/  _/    _/  _/_/  _/_/  _/    _/  _/        _/  _/
    _/    _/  _/_/_/_/  _/  _/  _/  _/_/_/_/    _/_/    _/_/
   _/    _/  _/    _/  _/      _/  _/    _/        _/  _/  _/
  _/_/_/    _/    _/  _/      _/  _/    _/  _/_/_/    _/    _/
 

 Roters et al., Computational Materials Science 158:420–478, 2019
 https://doi.org/10.1016/j.commatsci.2018.04.030

 Version: v3.0.0-alpha

 Compiled with: GCC version 7.5.0
 Compiler options: -cpp -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -iprefix /home/conda/feedstock_root/build_artifacts/damask_1600967332552/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/ -isysroot /home/conda/feedstock_root/build_artifacts/damask_1600967332552/_build_env/bin/../x86_64-conda-linux-gnu/sysroot -D_REENTRANT -D DAMASKVERSION="v3.0.0-alpha" -D Grid -D PETSc -isystem /srv/conda/envs/notebook/include -march=nocona -mtune=haswell -auxbase-strip CMakeFiles/DAMASK_grid.dir/DAMASK_interface.f90.o -O2 -O2 -pedantic-errors -Wall -Wextra -Wcharacter-truncation -Wunderflow -Wsuggest-attribute=pure -Wsuggest-attribute=noreturn -Wconversion-extra -Wimplicit-procedure -Wno-unused-parameter -std=f2008 -ftree-vectorize -fstack-protector-strong -fno-plt -ffunction-sections -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/damask_1600967332552/work=/usr/local/src/conda/damask-3.0.0 -fdebug-prefix-map=/srv/conda/envs/notebook=/usr/local/src/conda-prefix -fopenmp -fPIE -ffree-line-length-132 -fimplicit-none -ffpe-summary=all -fdefault-real-8 -fdefault-double-8

 Compiled on: Sep 24 2020 at 17:14:26

 Date: 07/10/2020
 Time: 12:39:36

 MPI processes:    1
 Host name: jupyter-vitesh13-2ddamask-5fworkflows-2dy9bp28yl
 User name: jovyan

 Command line call:      DAMASK_grid -l tensionX.load -g test.geom
 Geometry argument:      test.geom
 Load case argument:     tensionX.load
 Working directory:      /home/jovyan/Examples
 Geometry file:          test.geom
 Loadcase file:          tensionX.load
 Solver job name:        test_tensionX

 <<<+-  prec init  -+>>>
 Size of integer in bit:  32
   Maximum value:                 2147483647

 Size of float in bit:    64
   Maximum value:         0.180+309
   Minimum value:         0.223-307
   Decimal precision:     15

 <<<+-  IO init  -+>>>

 <<<+-  config init  -+>>>

 reading material.yaml

 ┌─────────────────────────────────────────────────────────────────────┐
 │                        warning                                      │
 │                         35                                          │
 ├─────────────────────────────────────────────────────────────────────┤
 │ could not get $DAMASK_NUM_THREADS                                   │
 │ BEGIN:      :END                                                    │
 │                                                                     │
 └─────────────────────────────────────────────────────────────────────┘
 using values from config.yaml file

 number of threads:             1


 <<<+-  math init  -+>>>
 size  of random seed:     33
 value of random seed:     642895683
 start of random sequence: 
                           0.12389714077249
                           0.31868404345012
                           0.10653430245563
                           0.03556151972965


 <<<+-  quaternions init  -+>>>

 <<<+-  rotations init  -+>>>

 Rowenhorst et al., Modelling and Simulation in Materials Science and Engineering 23:083501, 2015
 https://doi.org/10.1088/0965-0393/23/8/083501

 <<<+-  YAML_types init  -+>>>

 <<<+-  lattice init  -+>>>

 <<<+-  HDF5_Utilities init  -+>>>

 <<<+-  results init  -+>>>

 Diehl et al., Integrating Materials and Manufacturing Innovation 6(1):83–91, 2017
 https://doi.org/10.1007/s40192-017-0084-5

 <<<+-  discretization_grid init  -+>>>

 <<<+-  discretization init  -+>>>

 <<<+-  material init  -+>>>

 ┌─────────────────────────────────────────────────────────────────────┐
 │                        error                                        │
 │                        143                                          │
 ├─────────────────────────────────────────────────────────────────────┤
 │ no value found for key                                              │
 │ microstructure                                                      │
 │                                                                     │
 └─────────────────────────────────────────────────────────────────────┘

 DAMASK terminated on:
 Date:               07/10/2020
 Time:               12:39:36
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL IEEE_INEXACT_FLAG
STOP 1`

**Comment by jan-janssen** [comment]
Can you try:
```
export DAMASK_NUM_THREADS=2
```
before the damask call? maybe this environment variable needs to be set.

**Comment by vitesh13** [comment]
This environment variable gets set through config.yaml file if it is not specified. So this should be okay.
I will try out a material.yaml file where 'material' is replaced by 'microstructure' as before.

**Comment by vitesh13** [comment]
> This environment variable gets set through config.yaml file if it is not specified. So this should be okay.
> I will try out a material.yaml file where 'material' is replaced by 'microstructure' as before.

I tried out with a modified yaml file where the names were changed and it works! :)

As it doesnt affect the processing further, we can keep source/binary files as they are (because compiling newer source files might not be so straightforward) and always refer to latest python files.

**Comment by jan-janssen** [comment]
Nice, then I guess we can close this issue.

**Comment by jan-janssen** [comment]
I just tested the workflow on mybinder and everything works fine. It takes a bit long given the limited resources of mybinder (maybe it makes sense to reduce the system size) but apart from this I believe it is a great example to demonstrate how to connect DAMASK to jupyter notebooks.

**Comment by vitesh13** [comment]
I agree, it is a bit slow due to limited resources. Btw Muhammed made a docker which can run DAMASK along with pyiron.
I just had a brief look at it on Friday and it seems to run the DAMASK simulations. So this week I will migrate this workflow notebook to the docker and combine it with pyiron workflow which Liam has made to get elastic constants as a function of concentration. It should be quite interesting :)

**Comment by jan-janssen** [comment]
Sounds great - I look forward to it. I guess once we have this working it is definitely something we should also share with the directors to demonstrate the collaboration between the departments. Btw. do you have any information about the official release date for DAMASK 3.0 ? conda-forge is currently migrating to GCC 9.3 so this should also simplify the compatibility with the latest DAMASK version. https://conda-forge.org/status/#gcc930

**Comment by sharanroongta** [comment]
The data as far as I know has not been set yet. Although the next alpha version will be released soon (hopefully in a couple of weeks).
And I imagine the release date for DAMASK 3.0 should be sometime this year for sure. In any case, I shall confirm with Martin once.

**Comment by jan-janssen** [comment]
I created my own fork of this repository and I did not change anything, still I get the following error message:
```
 <<<+-  material init  -+>>>

 ┌─────────────────────────────────────────────────────────────────────┐
 │                        error                                        │
 │                        150                                          │
 ├─────────────────────────────────────────────────────────────────────┤
 │ index out of bounds                                                 │
 │ tNode_get_byIndex                                                   │
 │                                                                     │
 └─────────────────────────────────────────────────────────────────────┘
```

**Comment by sharanroongta** [comment]
That's weird. I just ran the simulation in the binder, and it was working.

**Comment by jan-janssen** [comment]
Yes, for me it is also working when I use the link in this repository, but when I fork the repository it no longer works.
